name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: zulu
          java-version: 8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Remove app.jar
        run: rm app/build/libs/app.jar
      - name: Create .env
        run: |
          cp .env.example app/build/libs
          mv app/build/libs/.env.example app/build/libs/.env
      - name: Create start.bat
        run: echo -e "@echo off\njava -jar bot.jar\nPAUSE" > app/build/libs/start.bat
      - name: Upload a release
        uses: actions/upload-artifact@v2.2.4
        with:
          name: release
          path: app/build/libs
